### PR TITLE
default run on a M2090

### PR DESCRIPTION
**Pull request by psteinb**
I am not quite sure why gearshifft ran with such little transforms, the K20Xm data has far more reach in terms of memory size, which knob can I turn to crank up the the shape of the transforms

### CODE REVIEW

**Comment by tdd11235813** [comment]
go to fixture_test_suite.hpp. there you find parameter for test extents. if you comment it out then standard set is loaded from fixture_test_suite_extents.hpp

**Comment by psteinb** [comment]
mmmmh, that is not so good. I think we should keep in mind, that we will only collect a lot of data, if it's easy to run tests from the command-line once gearshifft is compiled. Also, we should keep in mind that userX comes and wants to compare the runtimes for the one-and-only signal shape he always uses (which might not be part of the extents in the header files you referred to).

Everything is compile time based now (which almost denies us having a definition of the shape on the command-line) and gearshifft uses boost-utf underneath (so sneaking in or masking out command-line options might be tricky).

For now, I'd put all the shapes in that you used for the K20X. If a shape cannot be supported by a GPU (due to memory size), I'd skip the test and not produce any output.

**Comment by psteinb** [comment]
one more thing: can you please share the syntax that you used for the K20 benchmarks, or did you just comment out
https://github.com/mpicbg-scicomp/gearshifft/blob/master/inc/fixture_test_suite.hpp#L26

**Comment by tdd11235813** [comment]
for standard extents: just comment that highlighted line out. The lines below then include the standard set of extents.

shapes that are not supported (alloc fails) will automatically be skipped in the output. that test case with unsupported shape just fails and nothing will be written to the output. and yes, we need an interface for user-defined extents. Let's discuss this in the [enhancement issue](https://github.com/mpicbg-scicomp/gearshifft/issues/8).

**Comment by tdd11235813** [comment]
I would close this due to the heavy changes since then.

**Comment by psteinb** [comment]
fine with me!
P

**Pull request closed without merging**
