### PR TITLE
Latency of measurements improved

### PR DESCRIPTION
**Pull request by tdd11235813**
- latency improved
  + reuse timer objects and removed a device sync before new timings
- variable for warmup iterations added (not dumped to csv output yet)
- old random generator removed
  + at the moment data is initialized to 1s, see discussion below
- changed csv layout
  + column of 0s removed
  + column 'id' moved there, so column indices for timers stay the same
- the number of runs keeps at 5 because benchmarks did not show significant differences between 20 and 5 runs

result files have not been updated in this PR.

**Init the Data**
The initialization of the data happens when dimension changes. For large dimension it is quite time consuming. I just removed the old random number generator, because with C++14 we have better ones. But I also asked why we would need random numbers at all? The FFT timings are not related to values of the input data. 
However, it might be relevant for checking the correctness of FFT, so having data set to 1s is probably not a good thing.
If we want to use an advanced data generator, I want to know, if you would like to see an OpenMP parallelization in gearshifft. I already have a local branch for that and it has OpenMP for
 - data initialization
 - data validation

However, the random number generator is still not independent of the number of threads (so program is "broken"), so I have to ensure that the random numbers are the same regardless the number of threads used. What do you think?

### CODE REVIEW

**Comment by psteinb** [comment]
Hi ... I'd like to reproduce the 'timer timings' on our hardware first before merging this PR. 

I am inclined to reject having all `1` values in the data. I agree that generating say GBs of random numbers takes too much time. What we should do instead is generate fill e.g. 10% of in the input with random numbers and then shuffle the array. The reason is, that from my experience, filling the array with a constant value can obscure the sanity check, i.e. if the FFT was performed in the wrong way, you may not notice. And I believe this is one of the hallmarks of gearshifft, that every benchmark run does replicate a real use case. From my point of view, it's also fine to replace the `1` with a ramp (`a[0:6] = {0,1,2,3,4,5}`) or with a see-saw with a arbitrary period (`a[0:6] = {0,1,2,0,1,2}` from `a[i] = i % 3;` which would be a see-saw with period 3) or take a sinus function or ... but not a constant.

**Comment by tdd11235813** [comment]
thanks for your helpful feedback, so I'll play around with the explicit functions and later with C++14 randoms.
A ramp ( [0:N-1] ) is, however, not a good thing due to precision issues, so I take the see-saw for this PR. The commit comes in a minute.

**Comment by tdd11235813** [comment]
ok, now it uses initialization by values 
```
0.000 0.125 0.250 0.375 0.500 0.625 0.750 0.875 0.000 0.125 ...
```
let me know when you see further issues.

**Comment by tdd11235813** [comment]
If you checked the timings and things looking ok, let me know here.
This PR is a little bit messy, I gonna clean this and create a PR after your "OK".

**Comment by psteinb** [comment]
feel free to send the cleaned PR

**Pull request closed without merging**
