### PR TITLE
Updating gtx1080 results

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by psteinb** [comment]
Note, I discovered that the nvidia driver that was installed on the nodes, didn't yield the capability to set the application clocks of the GTX1080. we are in the process of updating the driver and hope that more recent versions can do that (this feature was removed by accident according to the devtalk forums)

**Comment by tdd11235813** [comment]
thanks for the update. the cuda8.0.44 and the clfft2.12.1 results can be removed as they are from an outdated gearshifft version.
The cuda 8.0.61 seems to be fine, could not see significant variances.
The clfft2.12.2 has some higher variances in the beginning, in the range of 15-30ms of total time.

clfft2 12 2_gtx1080

It seems it comes from the plan inits and to a smaller extent from the FFTs, but the outliers also can be seen on Plan Destroy and Allocation, but not on Download and Upload. So I am unsure, if this is a GPU or CPU only related influence. Was the node allocated exclusively ? (cannot see exclusive in the slurm script).

**Comment by psteinb** [comment]
yes, the node was used in exclusive mode, see [here](https://github.com/mpicbg-scicomp/gearshifft/pull/90/files#diff-45144c48763ba6d996acd43df73f44aaR4). I can always rerun and resubmit the clfft results as I agree that this looks a bit weird.

**Comment by tdd11235813** [comment]
ah ok, so the `clfft.slurm` can be removed, too. Regarding the clfft results, one would run several times to check the behaviour. It is probably a memory / cache thing. With default Slurm the core should be pinned due to the sbatch configuration and the frequency scaling should be set to highm1 by the srun launch. So, at that timescale such outliers are still likely and one could average the results of several launches to obtain a better picture. So you do not have to rerun, just remove the clfft.slurm.

**Comment by psteinb** [comment]
done, ready for merge then.

**Pull request merged**
