### PR TITLE
Human-readable DimKind & device type as program option & (row|col)major helper

### PR DESCRIPTION
**Pull request by tdd11235813**
- DimKind now really fixed ;)
- DimKind human-readable output
- device type as program option, example:

```
./gearshifft_clfft --run_test=*/float/*/Inplace_Real -- -e 32 -v -d cpu
```
- shape assignment helper for row and column major ordered arrays, see [traits.hpp](https://github.com/mpicbg-scicomp/gearshifft/compare/master...tdd11235813:Bugfixes?expand=1#diff-0db0305cbec0d530a15b3cdeec7500d6R6), example:

```
// cuFFT is column major
colmajor::assign(cufft_extents_, gearshifft_extents);
// clFFT is row major
rowmajor::assign(clfft_extents_, gearshifft_extents);
```

(gearshifft is column major, which means, last dimension is the fastest one.)
What do you think about this way of assignment, does it help readability?

### CODE REVIEW

**Comment by psteinb** [comment]
personally speaking, I not so much in favor of this solution. I'd encourage using move semantics or return by value (we are talking about 1-3 integers here!), possibly along the lines of:

```
// cuFFT is column major
auto cufft_will_use_this_shape_array = colmajor::assign(gearshifft_extents);
```

As gearshifft_extents is provided through CLI as far as I understood, there is still a non-negligible chance for users to be confused. Why don't we go for:

```
auto cufft_will_use_this_shape_array = interpret_as::column_major(gearshifft_extents);
```

or something similar, so that the meaning is crystal clear in the source code.

**Comment by tdd11235813** [comment]
yeah this would definitely improve readability. Now there are different types, so I have to tell the wanted return type. extents are of std::array<unsigned, NDim>, and clfft lib-interface wants size_t*, so it becomes cumbersome again. I have to think about it...

**Comment by psteinb** [comment]
:D well, to be honest and picky, I never liked `std::array<unsigned, 
NDim>` too much. using `unsigned` is so C++2003. ;) I'd encourage you to 
use std::uint32_t or similar as it's more cross-platform (in case we 
want to ship gearshifft to Win/OSX as well in the future).

Right now, I'd bite the bullet and cope with `size_t*` through 
intermediate objects:

`
namespace interpret_as
{

std::arraystd::uint32_t,NDim column_major(...){...}

}

void foo(const extent_type& e){

auto temp = interpret_as::column_major(e);

//std::arraystd::size_t,NDim fails2compile(temp.begin(),temp.end());
//std::arraystd::size_t,NDim fails2compiletoo = temp;

std::arraystd::size_t,NDim shape_to_use;
std::copy(temp.begin(),temp.end(),shape_to_use.begin()); //does type 
conversion at your own risk

}
`
the other option is to provide a template parameter to column_major, 
which always makes the default value ugly:

`
auto temp_with_default_type = interpret_as::column_major<>(e);
std::array<std::size_t,3> temp_with_default_type = 
interpret_as::column_major<std::size_t>(e);
`

**Comment by tdd11235813** [comment]
true, I also wanted to move away from unsigned, but I was thinking about size_t, and cufft interface actually wants int. I'll take std::uint32_t then. For the array cast maybe I employ [this thing](http://stackoverflow.com/questions/14279821/cast-an-stdarray-to-another-data-type-at-compile-time), have to play around a bit.
`interpret_as::column_major(gearshifft_extents);` would be the call for correct ordered and dimension independent read of gearshifft_extents. 
And if a cast is needed, then do a cast afterwards.

**Comment by psteinb** [comment]
sounds good, one more comment just came to my mind:
using size_t everywhere would make gearshift future proof as GPU VRAM 
gets larger by the month.
std::uint32_t will break/overflow already for a 1D float32_t array which 
is > 1GB (i.e. 2^32 elements) in memory! many of the fft libraries don't 
take that into account ... so clfft is ahead of the pack in that sense. 
And cufft/fftw are somehow still living in a 32-bit world.

**Comment by tdd11235813** [comment]
- DimKind now really fixed ;)
- DimKind human-readable output
- device type as program option, example:

```
./gearshifft_clfft --run_test=*/float/*/Inplace_Real -- -e 32 -v -d cpu
```

_Update 04/08/16_
- shape assignment helper for row and column major ordered arrays, example:

```
// cuFFT is column major
extents_ = interpret_as::column_major(cextents);
// clFFT is row major
auto cl_extents = interpret_as::row_major(cextents);
/// since cl_extents has always NDim=3, we do a copy
std::copy(cl_extents.begin(), cl_extents.end(), clLengths.begin());
```
- program option "--extent" | "-e" now also takes ',' as dimension separator besides of 'x'
- unsigned => size_t

**Comment by psteinb** [comment]
cool, thanks a bunch

**Pull request merged**
