### PR TITLE
OpenCL Timer. R evaluation/plotting script.

### PR DESCRIPTION
**Pull request by tdd11235813**
see commits for changes.
results will be updated soon.

### CODE REVIEW

**Comment by psteinb** [comment]
looks good to me. some minor questions:
- what is the reason behind not using a `unique_ptr`?
- thanks for the R script. that's a good basis for further development. I'd upgrade it with some ggplots2+dplyr magic 

btw, we could think about using a travisCI build to automatically test gearshifft [once the fftw part is in], maybe there is a way to run the rscript on the data within travisCI and commit the update back

**Comment by tdd11235813** [comment]
thanks,
unique_ptr: forgot to try it out^^. Looks like Context needs some constructor/assignment overload.
g2g, I update it soon, keep the PR open.
edit: travis sounds good, it's worth a try... do you have experiences with it?

**Comment by tdd11235813** [comment]
`unique_ptr` would mean to _move_ the ptr from global context instance to the specific fft-lib instance (Context::event <=> ClFFTImpl::context_.event), which invalidates the ptr in the global context and other fft-lib instances fail of course. 
I think the individual fft-lib instances shares that pointer given in the global context instance. so I would stay with the shared_ptr concept at the moment.

This event pointer is given to certain OpenCL commands and after being processed it contains eg. queue submission and processing time. It will be overwritten if you use it again on another command. My OpenCL Timer class waits for the event until its assigned command is finished, so no clash can occur as long as only one timer is active at a time. 

The proper way would be to have individual events for the timer in fft.hpp, however the client code is not aware of these timers (is actually intended). On the other hand, the client code has the OpenCL commands, where the event pointer is needed. 

In CUDA the events are queue-based, while in OpenCL the events are given to the commands directly. At the moment, the communication between timer and clfft client code is done via the single Context::event. 

This rather cumbersome design comes from the idea to keep the measurement layout fixed against the client code, so the client only cares about implementation of methods like execute_forward, upload, download ...
Maybe you have an idea how to build a better bridge? It is surely connected to the question how flexible gearshifft shall be in the future for client codes. We can discuss it in an issue if needed.

**Comment by psteinb** [comment]
Intersting, I didn't have this on my radar.

Let's keep this design for now. I think it provides quite some 
flexibility as you suggested.

**Comment by tdd11235813** [comment]
Just an addition on OpenCL timer as I did not look up properly. A colleague told me about marker in OpenCL: `clEnqueueMarker(queue, event)`
But OpenCL Standard 1.2 did not mention these marker functions, that they are usable for profiling. So I cannot time them (e.g. AMD OpenCL, [link](http://stackoverflow.com/questions/17091670/opencl-profiling-info-unavailable-for-marker-commands)).
Moreover, it would require to move the queue instance from fft benchmark instance to the context instance, which I do not really want at the moment. 
Current timer results are consistent with nvprof results.

**Pull request merged**
