### PR TITLE
Support mkl gnuwrapper

### PR DESCRIPTION
**Pull request by psteinb**
please comment on this PR, the app is running and producing results happily. I'll update this PR once the measurements on Haswell are in, so that we can have a look at it.

### CODE REVIEW

**Comment by psteinb** [comment]
just as a teaser, for a simple 1D 1024 signal and float-outofplace-real, mkl is 3x faster compared to fftw-measure with vanishing planning time. it will be interesting to see the changes across many input signals.

**Comment by tdd11235813** [comment]
wow cool, I am excited to see the diagrams. Code looks fine so far. If you have time you can add fftw version in `get_used_device_properties` in `fftw.hpp`.

**Comment by psteinb** [comment]
well, this exercises has uncovered another virtue of this benchmark. look what the mkl log files revealed:
```
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/9x9x27/Inplace_Real": Results mismatch: deviation=0.279385 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/9x9x27/Outplace_Real": Results mismatch: deviation=0.279385 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/9x27x27/Inplace_Real": Results mismatch: deviation=0.279316 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/9x27x27/Outplace_Real": Results mismatch: deviation=0.279316 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x27x27/Inplace_Real": Results mismatch: deviation=0.279325 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x27x27/Outplace_Real": Results mismatch: deviation=0.279325 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x27x81/Inplace_Real": Results mismatch: deviation=0.196383 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x27x81/Outplace_Real": Results mismatch: deviation=0.196383 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x81x81/Inplace_Real": Results mismatch: deviation=0.196383 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/27x81x81/Outplace_Real": Results mismatch: deviation=0.196383 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x81x81/Inplace_Real": Results mismatch: deviation=0.196382 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x81x81/Outplace_Real": Results mismatch: deviation=0.196382 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x81x243/Inplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x81x243/Outplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x243x243/Inplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/81x243x243/Outplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x243x243/Inplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x243x243/Outplace_Real": Results mismatch: deviation=0.373309 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x243x729/Inplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x243x729/Outplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x729x729/Inplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/243x729x729/Outplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/729x729x729/Inplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/729x729x729/Outplace_Real": Results mismatch: deviation=0.298187 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/729x729x2187/Inplace_Real": Results mismatch: deviation=0.150555 [1e-05]
benchmark_executor.hpp(76): fatal error: in "Fftw_mklwrapper/float/9x9x27/Inplace_Real": Results mismatch: deviation=0.279385 [1e-05]
```
Outofplace transforms through the same error. I am filing a bug report.

**Comment by tdd11235813** [comment]
very interesting. probably a padding issue, because this results mismatch only occurs for real 2d and 3d data?

i can confirm the planning time differences, see the plot here.
fftw-mkl

I think the multi-core issue of fftw planning is responsible for that. And maybe MKL does less in-depth search for the optimal plan.

The FFT processing is also faster with MKL, but not in all cases. In the end you see fftw performs better due to a better plan I guess. 
fftw-mkl-fft

I also have checked the other shapes and fftw outperforms MKL in pure FFT performance when it comes to bigger sizes. 

So the same conclusion here. If you need a plan over and over again, then use fftw and compute the optimal plan only once (fftw wisdoms). And you can stick to single core. If you need flexibility use clFFT or MKL. If you know you have big FFTs clFFT sometimes performs better than MKL. Otherwise, MKL outperforms clFFT.
clfft-mkl

**Comment by psteinb** [comment]
should we still merge this?

**Comment by tdd11235813** [comment]
I am not sure. We can merge this, but the error reasons are only visible in the raw files. In the diagrams you only would see gaps. How likely it is that the mismatch errors will be fixed soon? How reliable are these results when we have mismatch issues? I would leave this PR open.

**Comment by psteinb** [comment]
It's a bit hard to file a bug report with the MKL folks. I notified some people at Intel that I know. They haven't gotten around to me when they actually look at things. So for now, I suggest that we live with the gaps.

**Comment by psteinb** [comment]
I talked to Intel at and shortly before ISC. The bug that we ran into appears to be limited to the mkl from parallel studio xe `2017update4`. `2017update1` was fine with the reproducer I send to Intel. However the MKL devs I met invited me to get in touch directly with them and suggested to go for `2017update3`. whenever I get my hands on this version, I'll give it a try with gearshifft. still I wonder if we should go ahead and merge?

**Comment by tdd11235813** [comment]
thank you for the interesting update. Is xe 2017update4 the latest version? Hope it is fixed soon then. We can merge, but maybe a note in the README would be helpful, that the MKL results are probably suffering from the Intel XE 2017update4 bug and we update this when the bug is fixed.

**Comment by psteinb** [comment]
this PR is ready for merge. the more CPU based results we collect, the more important it will be to add information about the CPU model used. [compass](https://github.com/psteinb/compass) has become a single-header library since it's [last release](https://github.com/psteinb/compass/releases/tag/0.3.0).

**Comment by tdd11235813** [comment]
sorry for being silent on this, I want to test this PR on my own, however time has not been there yet.
The CPU hardware discovery in gearshifft is missing indeed for the FFTW part.
If you think, we can integrate compass, we can discuss the meta information structure of the gearshifft results header in an issue, and how to invoke compass to get consistent CPU information across the platforms.

**Comment by tdd11235813** [comment]
I took your branch and made some fixes and updates in a [PR](https://github.com/psteinb/gearshifft/pull/1), so it works with different compilers and versions.
Tested so far on taurus:
- Boost/1.66.0-intel-2018a, imkl/2018.1.163-iimpi-2018a, ...
- boost/1.66.0-intel2018.1.163-intelmpi2018, imkl/2018.1.163-iompi-2018a, ...
- boost/1.65.1-gnu5.5, mkl/2013, ... (_here the gnu fftwwrappers are used_)

**Comment by psteinb** [comment]
Superb. I'll see to merging it and let you know throw a comment here.

**Comment by psteinb** [comment]
I finally got around to look at this and test it. Thanks for the review,

**Pull request merged**
