### PR TITLE
201703 update p100 data

### PR DESCRIPTION
**Pull request by psteinb**
I was wondering if we want to remote:
```
results/P100-PCIE-16GB/clfft-2.12.2/clfft_gcc5.3.0_ubuntu14.0.4.3.csv  
results/P100-PCIE-16GB/cuda-8.0.44/cufft_gcc5.3.0_ubuntu14.0.4.3.csv
```
with this PR as well?

### CODE REVIEW

**Comment by tdd11235813** [comment]
you mean "remove"? Yeah, I think so, so remove them. Later on we can keep results from older gearshifft version and system environment, but not at this stage.
Btw, thanks for the results, I gonna transfer it into the publication right now.

**Comment by tdd11235813** [comment]
I have checked the results and the P100 is now very much slower.
But Initial GPU clock rate is the same, cufft version is the same. We need to check an example:
```
"CuFFT","Inplace","Complex","float",1,"powerof2",134217728,0,0,0,25,"Success",1.442962,2.035177,8.7e-05,394.49456787,17.07516861,17.033151627,300.23168945,1.156918,733.528196,1073741824,1073741824,1073741824
```
vs. old
```
"CuFFT","Inplace","Complex","float",1,"powerof2",134217728,0,0,0,"Success",0,1.44694,1.96964,7.3e-05,194.305,17.0752,17.0226,147.857,1.19759,381.012,1.07374e+09,1.07374e+09,1.07374e+09,25
```
gives:

| | Time_Allocation [ms] | Time_PlanInitFwd [ms] | Time_PlanInitInv [ms] | Time_Upload [ms] | Time_FFT [ms] | Time_iFFT [ms] | Time_Download [ms] | Time_PlanDestroy [ms] | Time_Total [ms] | Size_DeviceBuffer [bytes] | Size_DevicePlan [bytes] | Size_DeviceTransfer [bytes] |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| new | 1.442962 | 2.035177 | 8.7e-05 | **394.49456787** | 17.07516861 | 17.033151627 | **300.23168945** | 1.156918 | 733.528196 | 1073741824 | 1073741824 | 1073741824 | 
| old | 1.44694 | 1.96964 | 7.3e-05 | **194.305** | 17.0752 | 17.0226 | **147.857** | 1.19759 | 381.012 | 1.07374e+09 | 1.07374e+09 | 1.07374e+09 | 

So the memory transfers now took twice the time as before. Comparing with v0.1.0 code has not changed, [see here](https://github.com/mpicbg-scicomp/gearshifft/compare/v0.1.0...master#diff-5a9e95162ac042578a11c1e0f4c0e902). Amount of data transferred is also the same as before. I also plotted a graph and it seems the slowdown holds for each run.

So we have a problem now. Can you do some tests?
```
nvprof --print-gpu-trace ./gearshifft_cufft -e 134217728 -r */float/*/Inplace_Complex
./gearshifft_cufft -e 134217728 -r */float/*/Inplace_Complex -v
```
- Which memcopy bandwidth do you see reported by nvprof? 9-10 GB/s?
- Check the output and compare the Time Up/Download. I have on Taurus:
```
----------------------------------------------------------------------
Inplace, Complex, float, Dim=1, Kind=powerof2 (2), Ext=134217728
----------------------------------------------------------------------
        Time_Allocation [ms]:          1.06576 [avg]
       Time_PlanInitFwd [ms]:          1.59637 [avg]
       Time_PlanInitInv [ms]:        0.0001074 [avg]
            Time_Upload [ms]:          114.713 [avg]
               Time_FFT [ms]:          54.1699 [avg]
              Time_iFFT [ms]:          54.1404 [avg]
          Time_Download [ms]:          97.5537 [avg]
       Time_PlanDestroy [ms]:         0.849861 [avg]
             Time_Total [ms]:          324.152 [avg]
   Size_DeviceBuffer [bytes]:      1.07374e+09 [avg]
     Size_DevicePlan [bytes]:      1.07374e+09 [avg]
 Size_DeviceTransfer [bytes]:      1.07374e+09 [avg]
```
If you see the slowdown again, then something is wrong with the memory transfers. Maybe it helps to check with another program, with the bandwidthTest from the CUDA SDK. I attached an isolated version, just edit line 37 to your cuda path.

[bandwidthTest.zip](https://github.com/mpicbg-scicomp/gearshifft/files/870712/bandwidthTest.zip)

I got here:
```
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Tesla K80
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     11312.9

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     11358.5

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     169150.0

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

**Comment by psteinb** [comment]
something is fishy about this P100. 

```
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Tesla P100-PCIE-16GB
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     4000.3

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     2536.8

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     444415.5

Result = PASS
```

`nvidia-smi` reports that is uses PCIe gen3 x16, whereas the Titan X in the same enclosure uses PCI gen1 x16 (no typo) acoording to the tool. I think that makes these results bogus. and we should forget about them given the time constraints.

**Comment by psteinb** [comment]
I guess, I didn't pin the process (thanks to @jkelling for the reminder), check this minimal test out:

```
$ nvidia topo -m

        GPU0    GPU1    CPU Affinity
GPU0     X      SOC     0-5
GPU1    SOC      X      6-11
# die P100 ist GPU0
```

```
$ numactl -m0 -N0 bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Tesla P100-PCIE-16GB
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     12150.7

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     12890.6

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     443837.7


$ numactl -m1 -N1 bandwidthTest
CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Tesla P100-PCIE-16GB
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     3783.4

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     2539.2

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     443731.8

Result = PASS 
```

I am rerunning the benchmarks now

**Comment by psteinb** [comment]
I updated the GTX1080 results as well, P100 data still to come

**Comment by psteinb** [comment]
I just added a new version of the P100, from a first glance it looks very good.

**Comment by tdd11235813** [comment]
yes, looks good now. thanks a lot for your hard work. gonna update publication right now.

**Pull request merged**
