### PR TITLE
Use modern cmake.

### PR DESCRIPTION
**Pull request by tdd11235813**
Starting to modernize cmake files.
~~Also created a develop branch on upstream, so we can manage rollout of new versions (next milestone 0.4.0).~~ (following [trunkbaseddevelopment.com](https://trunkbaseddevelopment.com/))

Changelog 0.4.0:

- configure version number via cmake
- moved finders to cmake/modules
- cmake minimum requirement to 3.7
- targets will be built in subfolders
- packaging via cpack
- `CUDA_ENABLED` -> `CUFFT_ENABLED`, `OPENCL_ENABLED` -> `CLFFT_ENABLED`
- improves FindclFFT.cmake (searches in /usr, provides imported target)
- integrates gearshifft binaries in ctest
- uses `ctest` in travis
- `GEARSHIFFT_TESTS_ADD_CPU_ONLY` for CPU only tests (cufft targets cannot be run on travis)
- OpenMP cmake helper script `find_and_add_openmp`
- optional cmake superbuild 
  - ~~`cmake ../cmake/superbuild` runs superbuild~~
  - auto downloads, configures, builds and installs Boost, fftw, clfft, rocfft
  - aimed for static linking (Boost Test Framework mostly [is not properly compiled](https://www.boost.org/doc/libs/1_68_0/libs/test/doc/html/boost_test/adv_scenarios/static_lib_customizations/entry_point.html) for this)
  - aimed for easier packaging
  - planned to replace the travis scripts for such dependencies

...

### CODE REVIEW

**Comment by tdd11235813** [comment]
Another WIP stage. Open for testing.

**Comment by tdd11235813** [comment]
ready for merge, I think :)

**Comment by psteinb** [comment]
a lot of code to review. From scanning it, it looks very good. I feel an urge to just merge. I'll test locally first anyhow.

**Comment by tdd11235813** [comment]
yeah ok testing is a good thing, it is likely, that there are glitches.

**Comment by tdd11235813** [comment]
Incorporated rocFFT backend. Tested on AMD/HCC platform. No support for rocFFT/hipFFT->cuFFT at the moment. Fixed some other stuff. 
Superbuild is more flexible now, as external libraries can be kept in build folder (while downloads are always externally to avoid redownloading).
As rocFFT requires HCC on AMD, other backends might be build with a different compiler in a different build folder. 
However, packaging is currently not aware of that, as cmake does not allow to switch compiler during build generation. 
With superbuilds it is possible to cover that, ~~however packaging is currently not part of the superbuild layer. Currently, with superbuild, one still has to go down into gearshifft-build to call `make package`.~~

Edit: see subsequent commits. Refactored superbuild to make multi-arch packaging possible. Still some work to do for travis.

**Comment by tdd11235813** [comment]
travis tests passed. Readme updated. Going to self-merge (gearshifft to v0.4.0).
Edit: still needs some testing, of course ;)

**Pull request merged**
