### PR TITLE
Results and configs

### PR DESCRIPTION
**Pull request by tdd11235813**
keep this PR open, if you want to wait for results from fftw measure (10min time limit per plan).

you find config files for extents produced by script from https://github.com/mpicbg-scicomp/gearshifft_publication

### CODE REVIEW

**Comment by psteinb** [comment]
Super! Awesome PR. I'll hang in there for the FFTW_Measure results

**Comment by tdd11235813** [comment]
1D plans with fftw measure still take too long, I had to run further jobs with capped 1D extents, i.e.:

```
#radix 3
387420489 
1162261467
#radix 5
244140625 
1220703125
#radix7
282475249
```

are excluded.
I also started a less rigid version, where only `1162261467` and `1220703125` are excluded from the config file for 1D extents. Last case also has been applied to 1D plans for fftw estimate (result attached in commit 388adfe).
I also started versions with lower plan time limits (60s, 30s and 1s. For 1D only).
So I hope to add the last results here tomorrow or on Thursday, so we can merge.

**Comment by tdd11235813** [comment]
things have been messed up, so I have to close this.

**Comment by psteinb** [comment]
ok, looking forward to a new PR as we need the data

**Comment by tdd11235813** [comment]
working on new PR right now :)

**Comment by psteinb** [comment]
:D no pressure

**Pull request closed without merging**
